apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc 
spec:
  storageClassName: course-nfs-storage
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
